services:
  analytics-db:
    image: postgres:16
    container_name: analytics-db
    environment:
      POSTGRES_DB: analytics
      POSTGRES_USER: analytics
      POSTGRES_PASSWORD: analytics
    ports:
      - "5444:5432"
    volumes:
      - analytics-db-data:/var/lib/postgresql/data
    networks:
      - basit-network

  analytics-service:
    image: analytics-service:latest
    container_name: analytics-service
    build:
      context: ../../analytics-service
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://analytics-db:5432/analytics
      QUARKUS_DATASOURCE_USERNAME: analytics
      QUARKUS_DATASOURCE_PASSWORD: analytics
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8084:8084"
    depends_on:
      - analytics-db
      - analytics-kafka
    networks:
      - basit-network

  analytics-zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: analytics-zookeeper
    hostname: analytics-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2182:2181"
    networks:
      - basit-network

  analytics-kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: analytics-kafka
    hostname: analytics-kafka
    depends_on:
      - analytics-zookeeper
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://analytics-kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - basit-network

volumes:
  analytics-db-data:

networks:
  basit-network:
    external: true
