services:
  postgres:
    image: postgres:16
    container_name: notification-postgres
    hostname: notification-postgres
    environment:
      POSTGRES_DB: ${NOTIFICATION_DB_NAME}
      POSTGRES_USER: ${NOTIFICATION_DB_USER}
      POSTGRES_PASSWORD: ${NOTIFICATION_DB_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - basit-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: notification-zookeeper
    hostname: notification-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2189:2181"
    networks:
      - basit-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: notification-kafka
    hostname: notification-kafka
    depends_on:
      - zookeeper
    ports:
      - "9099:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2189"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://notification-kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - basit-network

  notification-service:
    build:
      context: ../../notification-service
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: notification-service
    depends_on:
      - postgres
      - kafka
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://notification-postgres:5432/${NOTIFICATION_DB_NAME}
      QUARKUS_DATASOURCE_USERNAME: ${NOTIFICATION_DB_USER}
      QUARKUS_DATASOURCE_PASSWORD: ${NOTIFICATION_DB_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

      NOVU_API_KEY: ${NOVU_API_KEY}
      QUARKUS_REST_CLIENT_NOVU_API_URL: https://api.novu.co
      QUARKUS_FLYWAY_MIGRATE_AT_START: "true"

      QUARKUS_OIDC_AUTH_SERVER_URL: ${OIDC_ISSUER_INTERNAL}
      QUARKUS_OIDC_CLIENT_ID: ${NOTIFICATION_OIDC_CLIENT_ID}
      QUARKUS_OIDC_TOKEN_AUDIENCE: api-gateway
    ports:
      - "8081:8080"
    networks:
      - basit-network

volumes:
  postgres_data:

networks:
  basit-network:
    external: true
